### ISSUE TITLE
Azure Vitual Desktop Ingration Configuration App

### ISSUE THREAD

**Issue by anonymous21155** [Azure/powerautomate-avd-starter-kit#15]
I am trying to setup Azure Virtual Desktop Integration Configuration App. Here I attached in screen shot . After the first step I am getting an error like this: GetSubscriptions.Run failed: { "error": { "code": 502, "source": "india-001.azure-apim.net", "clientRequestId": "8a50c2f6-e086-46f6-a822-76ae122fda6d", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08585256041614628202323796020CU22'." } } } }

**Comment by atsumiha** [comment]
Hi.
I got the same error.
Was it a permissions issue?

**Comment by anonymous21155** [comment]
I haven't included the client ID of both app registrations in key vault. So, I uploaded the client ID to the key vault, provided the secret name of client IDs in the configuration app as well as configured the necessary key vault access policy for both app registration to get and list the secrets.

**Comment by atsumiha** [comment]
Did your key vault access policy set full access for both apps? Or is it explained in some docs?
Thanks for answer.

**Comment by anonymous21155** [comment]
![Screenshot (260)](https://user-images.githubusercontent.com/115458734/220060727-b70c3139-5ab6-4a04-be3a-0999ff7f9f68.png)
You need to configure access policy for both apps, pls refer this doc: https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

**Comment by atsumiha** [comment]
Thank you for sharing information!
